"""common constants"""
import logging

log_format = "%(filename)s: %(message)s"
logging.basicConfig(format=log_format, level=logging.DEBUG)
LOGGER = logging.getLogger("haxo")
LOGGER.setLevel(logging.INFO)


SPDX = [
    "AAL",
    "AFL-3.0",
    "AGPL-3.0",
    "Apache-1.1",
    "Apache-2.0",
    "APL-1.0",
    "APSL-2.0",
    "Artistic",
    "Artistic-1.0",
    "Artistic-2.0",
    "BSD-1-Clause",
    "BSD-2-Clause",
    "BSD-2-Clause-Patent",
    "BSD-3-Clause",
    "BSD-3-Clause-LBNL",
    "BSD",
    "BSL-1.0",
    "CAL-1.0",
    "CATOSL-1.1",
    "CC0-1.0",
    "CDDL-1.0",
    "CECILL-2.1",
    "CNRI-Python",
    "CPAL-1.0",
    "CPL-1.0",
    "CUA-OPL-1.0",
    "CVW",
    "ECL-1.0",
    "ECL-2.0",
    "EFL-1.0",
    "EFL-2.0",
    "Entessa",
    "EPL-1.0",
    "EPL-2.0",
    "EUDatagrid",
    "EUPL-1.2",
    "Fair",
    "Frameworx-1.0",
    "GFDL",
    "GFDL-1.2",
    "GFDL-1.3",
    "GPL-1",
    "GPL-2",
    "GPL-2.0",
    "GPL-3",
    "GPL",
    "HPND",
    "Intel",
    "IPA",
    "IPL-1.0",
    "ISC",
    "LGPL-2",
    "LGPL-2.1",
    "LGPL-3",
    "LGPL-3.0",
    "LGPL",
    "LiLiQ-P",
    "LiLiQ-R",
    "LiLiQ-R+",
    "LPL-1.02",
    "LPPL-1.3c",
    "MirOS",
    "MIT",
    "Motosoto",
    "MPL-1.0",
    "MPL-1.1",
    "MPL-2.0",
    "MS-PL",
    "Ms-RL",
    "MS-RL",
    "MulanPSL - 2.0",
    "Multics",
    "NASA-1.3",
    "Naumen",
    "NCSA",
    "NGPL",
    "Nokia",
    "Nokia Open Source License",
    "NOSL",
    "NPOSL-3.0",
    "NTP",
    "OCLC-2.0",
    "ODbL",
    "OFL-1.1",
    "OGTSL",
    "OLDAP-2.8",
    "OSET-PL-2.1",
    "OSL-1.0",
    "OSL-2.1",
    "OSL-3.0",
    "PHP-3.0",
    "Plan9",
    "PostgreSQL",
    "Python-2.0",
    "PSF",
    "QPL-1.0",
    "RPL-1.1",
    "RPL-1.5",
    "RPSL-1.0",
    "RSCPL",
    "SimPL-2.0",
    "SISSL",
    "Sleepycat",
    "SPL-1.0",
    "UPL",
    "VSL-1.0",
    "W3C",
    "Watcom-1.0",
    "WXwindows",
    "Xnet",
    "YPL-1.1",
    "Zimbra-1.3",
    "Zlib",
    "ZPL-2.0",
]

if __name__ == "__main__":
    for license in SPDX:
        print(license)
